//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOP_IPHONE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressId { get; set; }
        public int AccountId { get; set; }
        public string RecipientName { get; set; }
        public string Phone { get; set; }
        public string Detail { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
