//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOP_IPHONE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Review()
        {
            this.ReviewImages = new HashSet<ReviewImage>();
        }
    
        public int review_id { get; set; }
        public int product_id { get; set; }
        public int account_id { get; set; }
        public int rating { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> Likes { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewImage> ReviewImages { get; set; }
    }
}
